### ISSUE TITLE
can you update the code with Room implementation 

### ISSUE THREAD

**Issue by Aman1kr** [jamalag/webrtc#3]
I want to say that when ever user comes on the hoe page he needs to enter in a room. All those clients are in that particular room will get the offer instead of every client on that website

**Comment by jamalag** [comment]
Sorry, never saw this msg. but this code was specifically for the initial video in the series: https://www.youtube.com/watch?v=h2WkZ0h0-Rc&list=PL_YW-znSZ_dK365WaVuiBUN6FYc9_1hni
